imported rpostgres build system

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,16 +1,107 @@
-#!/bin/sh
-RSCRIPT="${R_HOME}/bin${R_ARCH_BIN}/Rscript --vanilla"
-PG_VERSION=`$RSCRIPT ./src/get-pgversion.R`
-if [ "$PG_VERSION" -gt "8" ]
-then
-  echo "PKG_LIBS=-L`pg_config --libdir` -lpq" > ./src/Makevars
-  echo "PKG_CPPFLAGS=-I`pg_config --includedir`" >> ./src/Makevars
-else
-  $RSCRIPT ./src/get-libpq.R
-  if [ ! -e "./src/libpq.a" ]
-  then
-    echo "Failed to build libpq"
-    exit
-  fi
-  echo "PKG_LIBS=-L. -lpq" > ./src/Makevars
+#!/bin/bash
+# Anticonf (tm) script by Jeroen Ooms & Murat Tasan (2016)
+# This script will prefer cflags (specifically includefile dirs) and lib dirs
+# in the following order of precedence:
+#   (1) INCLUDE_DIR or LIB_DIR entered explicitly on the command line, e.g.
+#       R CMD INSTALL --configure-vars='INCLUDE_DIR=/.../include LIB_DIR=/.../lib'
+#   (2) Values found via 'pkg-config' for the libpq package.
+#   (3) Values found via 'pg_config' given a PostgreSQL installation.
+
+# Library settings
+PKG_CONFIG_NAME="libpq"
+PKG_DEB_NAME="libpq-dev"
+PKG_RPM_NAME="postgresql-devel"
+PKG_AMZ_RPM_NAMES="postgreql8-devel, psstgresql92-devel, postgresql93-devel, or postgresql94-devel"
+PKG_CSW_NAME="postgresql_dev"
+PKG_BREW_NAME="postgresql"
+PKG_TEST_HEADER="<libpq-fe.h>"
+PKG_LIBS="-lpq"
+PKG_LIBS_STATIC="-lpq -lssl -lcrypto -lldap"
+
+# pkg-config values (if available)
+if [ $(command -v pkg-config) ]; then
+  PKGCONFIG_CFLAGS=$(pkg-config --cflags --silence-errors ${PKG_CONFIG_NAME})
+  PKGCONFIG_LIBS=$(pkg-config --libs --silence-errors ${PKG_CONFIG_NAME})
 fi
+
+# pg_config vlaues (if available)
+if [ $(command -v pg_config) ]; then
+  PGCONFIG_INCLUDEDIR=$(pg_config --includedir)
+  PGCONFIG_LIBDIR=$(pg_config --libdir)
+fi
+
+if [ "$INCLUDE_DIR" ]; then
+  echo "Found INCLUDE_DIR!"
+  PKG_CFLAGS="-I$INCLUDE_DIR $PKG_CFLAGS"
+elif [ "$PKGCONFIG_CFLAGS" ]; then
+  echo "Found pkg-config cflags!"
+  PKG_CFLAGS=${PKGCONFIG_CFLAGS}
+elif [ "$PGCONFIG_INCLUDEDIR" ]; then
+  echo "Found pg_config includedir!"
+  PKG_CFLAGS="-I${PGCONFIG_INCLUDEDIR} $PKG_CFLAGS"
+fi
+
+if [ "$LIB_DIR" ]; then
+  echo "Found LIB_DIR!"
+  PKG_LIBS="-L$LIB_DIR $PKG_LIBS"
+elif [ "$PKGCONFIG_LIBS" ]; then
+  echo "Found pkg-config libs!"
+  PKG_LIBS=${PKGCONFIG_LIBS}
+elif [ "$PGCONFIG_LIBDIR" ]; then
+  echo "Found pg_config libdir!"
+  PKG_LIBS="-L${PGCONFIG_LIBDIR} $PKG_LIBS"
+fi
+
+if [ -z "$PKG_CFLAGS" ] && [ -z "$PKG_LIBS" ] && [[ "$OSTYPE" == "darwin"* ]]; then
+  if [ $(command -v brew) ]; then
+    BREWDIR=$(brew --prefix)
+  else
+    echo "Auto-brewing $PKG_BREW_NAME..."
+    BREWDIR="/tmp/homebrew"
+    rm -Rf $BREWDIR
+    mkdir -p $BREWDIR
+    curl -fsSL https://github.com/Homebrew/homebrew/tarball/master | tar xz --strip 1 -C $BREWDIR
+    HOMEBREW_CACHE="/tmp" $BREWDIR/bin/brew install --force-bottle openssl postgresql 2>&1 | perl -pe 's/Warning/Note/gi'
+    rm -f $BREWDIR/opt/*/lib/*.dylib
+  fi
+  PKG_CFLAGS="-I$BREWDIR/opt/postgresql/include"
+  PKG_LIBS="-L$BREWDIR/opt/{openssl,postgresql}/lib $PKG_LIBS_STATIC"
+fi
+
+# For debugging
+echo "Using PKG_CFLAGS=$PKG_CFLAGS"
+echo "Using PKG_LIBS=$PKG_LIBS"
+
+# Find compiler
+CC=$(${R_HOME}/bin/R CMD config CC)
+CFLAGS=$(${R_HOME}/bin/R CMD config CFLAGS)
+CPPFLAGS=$(${R_HOME}/bin/R CMD config CPPFLAGS)
+
+# Test configuration
+echo "#include $PKG_TEST_HEADER" | ${CC} ${CPPFLAGS} ${PKG_CFLAGS} ${CFLAGS} -E -xc - >/dev/null 2>&1 || R_CONFIG_ERROR=1;
+
+# Customize the error
+if [ $R_CONFIG_ERROR ]; then
+  echo "------------------------- ANTICONF ERROR ---------------------------"
+  echo "Configuration failed because $PKG_CONFIG_NAME was not found. Try installing:"
+  echo " * deb: $PKG_DEB_NAME (Debian, Ubuntu, etc)"
+  echo " * rpm: $PKG_RPM_NAME (Fedora, EPEL)"
+  echo " * rpm: $PKG_AMZ_RPM_NAMES (Amazon Linux)"
+  echo " * csw: $PKG_CSW_NAME (Solaris)"
+  echo " * brew: $PKG_BREW_NAME (OSX)"
+  echo "If $PKG_CONFIG_NAME is already installed, check that either:"
+  echo "(i)  'pkg-config' is in your PATH AND PKG_CONFIG_PATH contains"
+  echo "     a $PKG_CONFIG_NAME.pc file; or"
+  echo "(ii) 'pg_config' is in your PATH."
+  echo "If neither can detect $PGK_CONFIG_NAME, you can set INCLUDE_DIR"
+  echo "and LIB_DIR manually via:"
+  echo "R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'"
+  echo "--------------------------------------------------------------------"
+  exit 1;
+fi
+
+# Write to Makevars
+sed -e "s|@cflags@|$PKG_CFLAGS|" -e "s|@libs@|$PKG_LIBS|" src/Makevars.in > src/Makevars
+
+# Success
+exit 0
